export const image= {

Spotify:require('../Images/Spotify.png'),
Login:require('../Images/Login.png'),
facebook:require('../Images/facebook.png'),
google:require('../Images/google.png'),
phone:require('../Images/phone.png'),
Ed:require('../Images/Ed.jpg'),
LP:require('../Images/LinkinPark.jpg'),
Numb:require('../Images/numb.jpg'),
End:require('../Images/images.jpg'),
BE:require('../Images/believer.png'),
back:require('../Images/back.png'),
Button:require('../Images/Buttons.png'),
Imagine:require('../Images/Imagine.png'),
small:require('../Images/Small.png'),
req:require('../Images/playGreen.png'),
dot:require('../Images/dots.png'),
heart:require('../Images/heart.png'),
arrow:require('../Images/Arrow.png'),
Loop:require('../Images/Loop.png'),
Next:require('../Images/Next.png'),
Prev:require('../Images/Previous.png'),
shu:require('../Images/Shuffle.png'),
pause:require('../Images/pause1.png'),
share:require('../Images/Share.png'),
cast:require('../Images/Cast.png'),
}